
site:
  title: Tomasz Gerstel
  en_link: index_en.html
title: Tomasz Gerstel 
description: Junior Java | Fullstack Developer
google_analytics:
theme: jekyll-theme-leap-day
encoding: utf-8
lang: pl-PL
show_downloads: false
basewebsite: /pl.html
